### ISSUE TITLE
Understøtte iPhone 5/SE (screen-width: 320px)

### ISSUE THREAD

**Issue by andreasemil** [Pilen/fdfmaerker#26]
På forsiden vises der nu kun to kolonner med mærker.
Under et mærke vises der nu kun én kolonne med mærkeoplevelser.

**Comment by andreasemil** [comment]
![screen-with-320px_1](https://user-images.githubusercontent.com/43680974/46540162-cc2f7500-c8b8-11e8-9a73-8ed12a85cfb1.png)
![screen-with-320px_2](https://user-images.githubusercontent.com/43680974/46540163-cc2f7500-c8b8-11e8-9e76-8db6570dd125.png)

**Comment by Pilen** [comment]
Lige nu er kasserne en fast bredde, to gange denne bredde plus sidens margin er mere end telefonen, derfor vises kun en enkelt række.
Den korrekte løsning er noget med media queries til forskellige størrelser. Noget med at den så kan justere bredden inde for nogle intervaller. 

Samtidigt bør man så kigge på at placere dem korrekt horisontalt f.eks centret

**Comment by Pilen** [comment]
Det "komplicerede" er at fastholde aspect ratio.

Det samme skal gøres i forhold til #25
