### ISSUE TITLE
Skjul standardtekst på distancemærker

### ISSUE THREAD

**Issue by andreasemil** [Pilen/fdfmaerker#30]
Følgende skal ikke vises på distancemærker:
_For hver mærkeoplevelse I tager, stiger I et mærketal. I vælger selv rækkefølgen og kan godt styrke læringen i en mærkeoplevelse ved at arbejde med den igen senere._

**Comment by Pilen** [comment]
Typisk...

**Comment by Pilen** [comment]
Note, lav en separat template til distance mærker
