### ISSUE TITLE
Ny tekst til oplevelsesmærker

### ISSUE THREAD

**Issue by andreasemil** [Pilen/fdfmaerker#37]
Vores mærker på skjorten har tal, der viser hvor mange mærkeoplevelser vi har haft. Med dem kan vi mindes oplevelserne, vi har haft sammen. I vælger selv rækkefølgen på mærkeoplevelserne, og for hver af dem stiger mærketallet med én. I kan godt arbejde med en mærkeoplevelse igen senere.

**Comment by andreasemil** [comment]
PS: Nice ny font 👍  :)

**Comment by Pilen** [comment]
Du skal i virkeligheden bare oprette en fil mærkesidetekst.txt ligesom forsidetekst.txt

Er fonten blevet ændret?

**Comment by andreasemil** [comment]
Den nye tekst ligger nu i mærkesidetekst.txt (samme mappeplacering som forsidetekst.txt).

Sorry, mine øjne narrede mig - nevermind
